export const WEB_PROTOCOL = PRINCE_DUALS_WEB_PROTOCOL;
export const WEB_DOMAIN = PRINCE_DUALS_WEB_DOMAIN;
export const WEB_PORT = PRINCE_DUALS_WEB_PORT;
export const WS_PROTOCOL = PRINCE_DUALS_WS_PROTOCOL;
export const WS_PORT = PRINCE_DUALS_WS_PORT;
export const OFFLINE_MODE = PRINCE_DUALS_OFFLINE_MODE;
